/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package higopproject;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class Login extends javax.swing.JPanel {
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        un_fld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pw_fld = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        un_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                un_fldActionPerformed(evt);
            }
        });
        jPanel1.add(un_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 63, 154, -1));

        jLabel1.setText("username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 97, -1, -1));

        pw_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_fldActionPerformed(evt);
            }
        });
        jPanel1.add(pw_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 142, 154, -1));

        login_btn.setText("LOGIN");
        login_btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel1.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 70, 30));

        jLabel2.setText("password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 176, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 390, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/higopproject/higopproject/gradient.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void clearTextFields(){
        un_fld.setText("");
        pw_fld.setText("");
    }
    private void un_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_un_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_un_fldActionPerformed

    private void pw_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw_fldActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        String user = un_fld.getText();
        String passString = new String(pw_fld.getPassword());

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos?useSSL=false", "root", "");
            String query = "SELECT * FROM regform WHERE username = ? AND password = ?";
            PreparedStatement pstmt = (PreparedStatement) con.prepareStatement(query);
            pstmt.setString(1, user);
            pstmt.setString(2, passString);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                int userID = rs.getInt("staff_id"); 

                String insertLoginHistory = "INSERT INTO login_history (username, login_time) VALUES (?, NOW())";
                PreparedStatement insertPstmt = (PreparedStatement) con.prepareStatement(insertLoginHistory);
                insertPstmt.setString(1, user);
                insertPstmt.executeUpdate();

                Home portal = new Home(userID, user); 
                portal.setVisible(true);

                ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid username or password!");
                clearTextFields(); 
            }
        } catch (Exception e) {
            e.printStackTrace();  
        }
    }//GEN-LAST:event_login_btnActionPerformed
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame frame = new javax.swing.JFrame();
                frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                frame.setLayout(new java.awt.GridBagLayout());
                
                Login loginPanel = new Login();
                
                java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
                gbc.gridx = 0; 
                gbc.gridy = 0; 
                gbc.anchor = java.awt.GridBagConstraints.CENTER; 
                gbc.fill = java.awt.GridBagConstraints.NONE; 
                gbc.insets = new java.awt.Insets(50, 50, 50, 50); 
                
                frame.add(loginPanel, gbc);
                frame.pack();
                frame.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField pw_fld;
    private javax.swing.JTextField un_fld;
    // End of variables declaration//GEN-END:variables

}
