/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package higopproject;

import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.text.DecimalFormat;
import javax.swing.*;
import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class purchase extends javax.swing.JPanel {

    public purchase() {
        initComponents();
        
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(300);
    }
    
    public void addtable(int id, String name, int Qty, double Price){

        DefaultTableModel dt = (DefaultTableModel) jTable2.getModel();
       DecimalFormat df = new DecimalFormat("0.0");
       
        //cal
        int numOfRow = jTable2.getRowCount();
        double totprice = Price * Double.valueOf(Qty);
        String TotalPrice = df.format(totprice);
    
    
        //rows
        for(int row = 0; row < jTable2.getRowCount(); row++){
        if (name == jTable2.getValueAt(row,1)){
            dt.removeRow(jTable2.convertRowIndexToModel(row));

            }
        }
    
        Vector v = new Vector(); 
        v.add(id);
        v.add(name);
        v.add(Qty);
        v.add(TotalPrice );
        dt.addRow(v);
    }
    public void cal(){
        int numOfRow = jTable2.getRowCount();
        double tot = 0.0;
    
        for (int i=0; i < numOfRow; i++){
            double value = Double.valueOf(jTable2.getValueAt(i, 3).toString());
            tot += value;
        }
        DecimalFormat df = new DecimalFormat("0.0");
        total.setText(df.format(tot));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        burger = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        asd = new javax.swing.JButton();
        asdf = new javax.swing.JButton();
        asdfg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Void = new javax.swing.JLabel();
        q1 = new javax.swing.JTextField();
        q12 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q7 = new javax.swing.JTextField();
        q8 = new javax.swing.JTextField();
        q6 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q9 = new javax.swing.JTextField();
        q11 = new javax.swing.JTextField();
        q10 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        q5 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        pay_btn = new javax.swing.JButton();
        print_btn = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        VOID = new javax.swing.JButton();
        Void1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(1630, 736));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        burger.setBackground(new java.awt.Color(102, 102, 255));
        burger.setText("Burger");
        burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerActionPerformed(evt);
            }
        });
        jPanel2.add(burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 50, 130, 53));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Chili Garlic Sauce");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 53));

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setText("Special Batchoy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 120, 53));

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setText("Regular");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 80, 50));

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setText("Large");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 80, 48));

        jButton8.setBackground(new java.awt.Color(255, 102, 255));
        jButton8.setText("12OZ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, 50));

        jButton9.setBackground(new java.awt.Color(255, 102, 255));
        jButton9.setText("16OZ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 80, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Fries");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Pearl Coolers");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 180, -1, -1));

        asd.setBackground(new java.awt.Color(153, 153, 0));
        asd.setText("Beef");
        asd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asdActionPerformed(evt);
            }
        });
        jPanel2.add(asd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 80, 54));

        asdf.setBackground(new java.awt.Color(153, 153, 0));
        asdf.setText("Pork");
        asdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asdfActionPerformed(evt);
            }
        });
        jPanel2.add(asdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 80, 54));

        asdfg.setBackground(new java.awt.Color(153, 153, 0));
        asdfg.setText("Japanese");
        asdfg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asdfgActionPerformed(evt);
            }
        });
        jPanel2.add(asdfg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 100, 54));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("SIOMAI");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));
        jPanel2.add(Void, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 346, -1, -1));
        jPanel2.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, -1));
        jPanel2.add(q12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));
        jPanel2.add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 120, -1));
        jPanel2.add(q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, -1));
        jPanel2.add(q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 80, -1));
        jPanel2.add(q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 80, -1));
        jPanel2.add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 80, -1));
        jPanel2.add(q9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 80, -1));
        jPanel2.add(q11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 100, -1));
        jPanel2.add(q10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 80, -1));

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setText("Siopao");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 100, 50));
        jPanel2.add(q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 100, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("CLEAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, -1, -1));

        jTable2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item", "Qty", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        b.setColumns(20);
        b.setRows(5);
        jScrollPane1.setViewportView(b);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TOTAL:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CASH:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CHANGE:");

        bal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bal.setText("00");

        total.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        total.setText("00");

        pay_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pay_btn.setText("PAY");
        pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btnActionPerformed(evt);
            }
        });

        print_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        print_btn.setText("PRINT");
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton19.setText("DELETE");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        VOID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VOID.setText("VOID");
        VOID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOIDActionPerformed(evt);
            }
        });

        Void1.setText("0");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bal)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(VOID)
                        .addGap(6, 6, 6)
                        .addComponent(jButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(pay_btn)
                                .addGap(18, 18, 18)
                                .addComponent(print_btn))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(Void1)))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(total))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(bal)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton19)
                            .addComponent(VOID)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Void1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(157, 157, 157))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clearTextFields();
        clearLabels();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOIDActionPerformed
        int i = Integer.valueOf(Void1.getText());
        Void1.setText(String.valueOf(i));
        cal();
    }//GEN-LAST:event_VOIDActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        DefaultTableModel dt = (DefaultTableModel) jTable2.getModel();
        String r = dt.getValueAt(jTable2.getSelectedRow(), 0).toString();

        int  rw = jTable2.getSelectedRow();
        dt.removeRow(rw);

        System.out.print(r);
        switch(r){
            case "1":
            q12.setText("0");
            break;
            case "2":
            q1.setText("0");
            break;
            case "3":
            q3.setText("0");
            break;
            case "4":
            q4.setText("0");
            break;
            case "5":
            q5.setText("0");
            break;
            case "6":
            q3.setText("0");
            break;
            case "7":
            q7.setText("0");
            break;
            case "8":
            q8.setText("0");
            break;
            case "9":
            q9.setText("0");
            break;
            case "10":
            q10.setText("0");
            break;
            case "11":
            q11.setText("0");
            break;
            case "Void1":
            Void1.setText("0");
            break;

            default:
            System.out.println("Over");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed

        double tot = Double.valueOf(total.getText());
        double pp = Double.valueOf(cash.getText());
        double ball = pp - tot;

        DecimalFormat dfFormat = new DecimalFormat("0.0");

        try {
            b.setText("           \t  Higop Cafe  \n");
            b.setText(b.getText() + "\t Official Receipt  \n");
            b.setText(b.getText() + "============================================" + "\n");
            b.setText(b.getText() + "Item \t\tQty \tPrice" + "\n");

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

            if (ball < 0) {
                JOptionPane.showMessageDialog(null, "Error: Insufficient cash provided.", "Transaction Error", JOptionPane.ERROR_MESSAGE);
            } else if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Error: Please select a Product.", "Transaction Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Connection con = null;
                PreparedStatement ps = null;
                try {
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos", "root", "");

                    for (int i = 0; i < model.getRowCount(); i++) {
                        String Name = model.getValueAt(i, 1).toString().trim();
                        int Qty = Integer.parseInt(model.getValueAt(i, 2).toString());

                        String Price = model.getValueAt(i, 3).toString();
                        b.setText(b.getText() + Name + "\t" + "\t" + Qty + "\t" + Price + "\n");

                        String sql = "UPDATE product SET qty = qty - ? WHERE product_name = ?";
                        ps = con.prepareStatement(sql);
                        ps.setInt(1, Qty);
                        ps.setString(2, Name);

                        int rowsUpdated = ps.executeUpdate();

                        if (rowsUpdated == 0) {
                            JOptionPane.showMessageDialog(null, "Error: Could not update product " + Name, "Database Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }

                    bal.setText(dfFormat.format(ball));
                    b.setText(b.getText() + "============================================" + "\n");
                    b.setText(b.getText() + "Sub Total : " + total.getText() + "\n");
                    b.setText(b.getText() + "Cash : " + cash.getText() + "\n");
                    b.setText(b.getText() + "Change : " + bal.getText() + "\n");
                    b.setText(b.getText() + "============================================" + "\n");

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                } finally {
                    // Close resources
                    try {
                        if (ps != null) ps.close();
                        if (con != null) con.close();
                    } catch (SQLException ex) {
                        System.out.println("Error closing the connection: " + ex.getMessage());
                    }
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_print_btnActionPerformed

    private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btnActionPerformed

        try {
            if (total.getText().isEmpty() || Double.valueOf(total.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "None of the products is selected.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double tot = Double.valueOf(total.getText());
            double pp = Double.valueOf(cash.getText());
            double ball = pp - tot;

            DecimalFormat df = new DecimalFormat("0.0");

            if (ball < 0) {
                JOptionPane.showMessageDialog(null, "Error: Insufficient cash provided.", "Transaction Error", JOptionPane.ERROR_MESSAGE);
            } else {
                bal.setText(String.valueOf(df.format(ball)));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Please enter valid numbers for cash and total.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pay_btnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //siopao
        if (q5.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q5.getText());
                addtable(8, "Siopao", i, 28.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void asdfgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asdfgActionPerformed
        //japanese siomai
        if (q11.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q11.getText());
                addtable(10, "Jpnese/Siomai", i, 38.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();
    }//GEN-LAST:event_asdfgActionPerformed

    private void asdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asdfActionPerformed
        // pork siomai
        if (q10.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q10.getText());
                addtable(11, "Pork/Siomai", i, 35.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();
    }//GEN-LAST:event_asdfActionPerformed

    private void asdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asdActionPerformed
        // beef siomai
        if (q9.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q9.getText());
                addtable(9, "Beef/Siomai", i, 35.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_asdActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //pearl coolers 16oz
        if (q8.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q8.getText());
                addtable(5, "Coolers/16oz", i, 48.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //pearl cooloers 12oz
        if (q7.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q7.getText());
                addtable(4, "Coolers/12oz", i, 35.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //large fries
        if (q6.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q6.getText());
                addtable(6, "Large/Fries", i, 50.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //regular fries function
        if (q3.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q3.getText());
                addtable(7, "Regular/Fries", i, 40.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //batchoy function
        if (q4.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q4.getText());
                addtable(3, "Special Batchoy", i, 69.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //chili sauce function
        if (q12.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q12.getText());
                addtable(1, "Chili Sauce", i, 110.00);
                cal();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
        //burger function
        if (q1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int i = Integer.valueOf(q1.getText());
                addtable(2, "Burger", i, 30.00);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please input a valid quantity.", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cal();
    }//GEN-LAST:event_burgerActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        clearLabels();
    }//GEN-LAST:event_jButton7ActionPerformed
    private void clearLabels(){
        q1.setText("");
        q12.setText("");
        q3.setText("");
        q4.setText("");
        q5.setText("");
        q6.setText("");
        q7.setText("");
        q8.setText("");
        q9.setText("");
        q10.setText("");
        q11.setText("");
        Void1.setText("0");
    }
    private void clearTextFields() {
        cash.setText(""); 
        b.setText("");     
        total.setText(""); 
        bal.setText("");   
        
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {}, 
            new String [] {"ID", "Item", "Qty","Price"}  
        ));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VOID;
    private javax.swing.JLabel Void;
    private javax.swing.JLabel Void1;
    private javax.swing.JButton asd;
    private javax.swing.JButton asdf;
    private javax.swing.JButton asdfg;
    private javax.swing.JTextArea b;
    private javax.swing.JLabel bal;
    private javax.swing.JButton burger;
    private javax.swing.JTextField cash;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton pay_btn;
    private javax.swing.JButton print_btn;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q10;
    private javax.swing.JTextField q11;
    private javax.swing.JTextField q12;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    private javax.swing.JTextField q6;
    private javax.swing.JTextField q7;
    private javax.swing.JTextField q8;
    private javax.swing.JTextField q9;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
